### ISSUE TITLE
0.1 Milestone

### ISSUE THREAD

**Issue by cdj2112** [cdj2112/Game-Grid#1]
- [x] Add Pieces to Grid
- [x] Move Pieces With Arrow Buttons
- [x] Change Pieces Colors
- [x] Calculate and Display Move Distance
- [x] Piece Collision
